### ISSUE TITLE
这源每次加载都要几分钟

### ISSUE THREAD

**Issue by 10fun** [liu673cn/box#12]
这源每次加载都要几分钟

**Comment by liu673cn** [comment]
国外仓库，加载慢，内容有点多，适当自己精简 。
https://cdn.jsdelivr.net/gh/liu673cn/box@main/m.json

**Comment by 10fun** [comment]
> 国外仓库，加载慢，内容有点多，适当自己精简 。 https://cdn.jsdelivr.net/gh/liu673cn/box@main/m.json



> 国外仓库，加载慢，内容有点多，适当自己精简 。 https://cdn.jsdelivr.net/gh/liu673cn/box@main/m.json

换这个是快了点。但手机上可以，电视上就jar失败
