### ISSUE TITLE
tvbox配置文件jar路径

### ISSUE THREAD

**Issue by cyao2q** [liu673cn/box#19]
tvbox配置文件jar路径
你的项目开通了 github pages 完全可以使用pages里面的jar路径 比如 https://raw.liucn.cc/box/sub/jar/box285.jar;md5;34ED41FF20791444998C5C9D3476131B
我是研究你的项目才会使用 github pages 很感谢

我的分享主页 https://f.cyao.tk/

**Comment by cyao2q** [comment]
同样 你的所有 xpath文件也可以使用 github pages的路径

**Comment by liu673cn** [comment]
👍
