### ISSUE TITLE
配置解析失败，是不是jar的问题

### ISSUE THREAD

**Issue by smallmagpie** [liu673cn/box#23]
换了几个版本都有这个问题，之前好好的，今天来更新下jar然后就这样了

**Comment by smallmagpie** [comment]
目前确定不是jar的问题了，经过测试，在猫影视配置编辑器格式化代码后，解析配置会失败，待进一步确认

**Comment by liu673cn** [comment]
语法  某段缺少  " , } 这些字符，或者多了
