### ISSUE TITLE
最新版安装包在安卓4.0点TV安装解析失败

### ISSUE THREAD

**Issue by MiyouQ** [liu673cn/box#25]
老版本安装包家里老的海信电视安卓4.0和shieldTV安卓7.0都能安装，最新版的安装包安卓4.0点海信电信就提示安装解包失败。
这是最新版不支持安卓4.0了嘛。

**Comment by liu673cn** [comment]
新版对4.0  是有安装问题

**Comment by happyin123** [comment]
为什么同样的配置地址在安卓手机可以使用，在小米盒子上却显示：拉取配置失败？ @liu673cn
